on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: graphmeql.azurecr.io
        username: ${{ secrets.acr_graphmeql_username }}
        password: ${{ secrets.acr_graphmeql_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/client" -f  "client/Dockerfile" -t graphmeql.azurecr.io/myakscluster:${{ github.sha }}
        docker push graphmeql.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myakscluster2920 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myakscluster2920`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myakscluster2920
        container-registry-url: graphmeql.azurecr.io
        container-registry-username: ${{ secrets.acr_graphmeql_username }}
        container-registry-password: ${{ secrets.acr_graphmeql_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: myakscluster2920
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          graphmeql.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth